fix for logname failing

diff --git a/common/modprobed-db.in b/common/modprobed-db.in
--- a/common/modprobed-db.in
+++ b/common/modprobed-db.in
@@ -15,9 +15,37 @@ if [[ ! -f $SKEL ]]; then
 	exit 1
 fi
 
-# We need to keep book on which user runs this script invoking it via sudo
-USER=$(logname)
+# Under normal circumstances, logname is used to identify the user
+# who ran this script.  For some configurations, (rare) logname will fail to
+# return this piece of data so we use whoami to get the user name.
+
+logname &>/dev/null
+if [[ $? -eq 0 ]]; then
+  USER=$(logname)
+else
+  if [[ $EUID -eq 0 ]]; then
+    # running as root
+    USER="$SUDO_USER"
+  else
+    # not running as root
+    USER=$(whoami)
+  fi
+fi
+
+if [[ -z "$USER" ]]; then
+	echo 'ERROR: Cannot figure out who ran this script.'
+	echo 'Bailing out.'
+	exit 1
+fi
+
 HOMEDIR="$(getent passwd $USER | cut -d: -f6)"
+
+if [[ ! -d "$HOMEDIR" ]]; then
+	echo 'ERROR: Cannot locate user home directory'
+	echo 'Bailing out.'
+	exit 1
+fi
+
 CFG_FILE=$HOMEDIR/.config/modprobed-db.conf
 
 # name change from modprobed_db --> modprobed-db so move existing configs
